In [1]:
import requests 
from bs4 import BeautifulSoup

In [2]:
result = requests.get("https://keur-immo.com/senegal/")
recup = result.text
data = BeautifulSoup(recup, "html.parser")

In [3]:
annonces = data.find_all("article", class_="g5core__gutter-item")
len(annonces)

36

In [4]:
text = annonces[0].find("h3", class_="g5ere__loop-property-title").text
print(text)

DAKAR MAMELLES : Terrain à vendre 2 hectares

In [5]:
prix = annonces[0].find("span", class_="g5ere__lpp-price").text
print(prix)

31 600 000 000 FCFA

In [6]:
chambre = annonces[0].find("span", class_="g5ere__property-bedrooms")
print(chambre)
bain = annonces[0].find("span", class_="g5ere__loop-property-bathrooms")
print(bain)
surface = annonces[0].find("span", class_="g5ere__loop-property-size")
print(surface)

None
None
None

In [7]:
import pandas as pd
df = pd.read_csv("nigeria_houses_data.csv")
df.head()

,bedrooms,bathrooms,toilets,parking_space,title,town,state,price
0,6.0,5.0,5.0,4.0,Detached Duplex,Mabushi,Abuja,450000000.0
1,4.0,5.0,5.0,4.0,Terraced Duplexes,Katampe,Abuja,800000000.0
2,4.0,5.0,5.0,4.0,Detached Duplex,Lekki,Lagos,120000000.0
3,4.0,4.0,5.0,6.0,Detached Duplex,Ajah,Lagos,40000000.0
4,4.0,4.0,5.0,2.0,Semi Detached Duplex,Lekki,Lagos,75000000.0

In [8]:
df.info

<bound method DataFrame.info of        bedrooms  bathrooms  toilets  parking_space                 title  \
0           6.0        5.0      5.0            4.0       Detached Duplex
1           4.0        5.0      5.0            4.0     Terraced Duplexes
2           4.0        5.0      5.0            4.0       Detached Duplex
3           4.0        4.0      5.0            6.0       Detached Duplex
4           4.0        4.0      5.0            2.0  Semi Detached Duplex
...         ...        ...      ...            ...                   ...
24321       2.0        2.0      2.0            4.0        Block of Flats
24322       4.0        5.0      5.0            4.0        Block of Flats
24323       4.0        5.0      5.0            4.0       Detached Duplex
24324       3.0        4.0      4.0            3.0        Block of Flats
24325       4.0        5.0      5.0            4.0       Detached Duplex

                       town  state        price
0                   Mabushi  Abuja  450000000.0
1                   Katampe  Abuja  800000000.0
2                     Lekki  Lagos  120000000.0
3                      Ajah  Lagos   40000000.0
4                     Lekki  Lagos   75000000.0
...                     ...    ...          ...
24321                Kabusa  Abuja   15000000.0
24322           Ado-Odo/Ota   Ogun   25000000.0
24323                 Lekki  Lagos   68000000.0
24324  Victoria Island (VI)  Lagos   78000000.0
24325                 Lekki  Lagos   65000000.0

[24326 rows x 8 columns]>

In [9]:
df.isnull().sum()

bedrooms         0
bathrooms        0
toilets          0
parking_space    0
title            0
town             0
state            0
price            0
dtype: int64

In [10]:
df.describe()

           bedrooms     bathrooms       toilets  parking_space         price
count  24326.000000  24326.000000  24326.000000   24326.000000  2.432600e+04
mean       4.338814      4.600798      5.176355       4.041725  3.013802e+08
std        1.138497      1.163161      1.226253       1.399936  1.220403e+10
min        1.000000      1.000000      1.000000       1.000000  9.000000e+04
25%        4.000000      4.000000      5.000000       4.000000  5.200000e+07
50%        4.000000      5.000000      5.000000       4.000000  8.500000e+07
75%        5.000000      5.000000      6.000000       4.000000  1.600000e+08
max        9.000000      9.000000      9.000000       9.000000  1.800000e+12

In [11]:
# 1. Calcul du seuil des 99%
seuil = df['price'].quantile(0.99)
print(f"Le prix limite (quantile 0.99) est de : {seuil:,.2f} NGN")

# 2. Filtrage du DataFrame
df_clean = df[df['price'] < seuil]

# 3. Comparaison du prix moyen
print(f"Ancienne moyenne : {df['price'].mean():,.2f} NGN")
print(f"Nouvelle moyenne nettoyée : {df_clean['price'].mean():,.2f} NGN")

Le prix limite (quantile 0.99) est de : 1,400,000,000.00 NGN
Ancienne moyenne : 301,380,208.47 NGN
Nouvelle moyenne nettoyée : 145,990,331.30 NGN

In [12]:
df_clean.describe()

           bedrooms     bathrooms       toilets  parking_space         price
count  24000.000000  24000.000000  24000.000000   24000.000000  2.400000e+04
mean       4.325208      4.588750      5.167417       4.037833  1.459903e+08
std        1.124352      1.151454      1.213617       1.392833  1.833203e+08
min        1.000000      1.000000      1.000000       1.000000  9.000000e+04
25%        4.000000      4.000000      5.000000       4.000000  5.000000e+07
50%        4.000000      5.000000      5.000000       4.000000  8.500000e+07
75%        5.000000      5.000000      6.000000       4.000000  1.550000e+08
max        9.000000      9.000000      9.000000       9.000000  1.395000e+09

In [13]:
len(df) - len(df_clean)

326

In [14]:
print(df_clean['town'].unique())
print(df_clean['state'].unique())
print(df_clean['title'].unique())

<StringArray>
[             'Mabushi',              'Katampe',                'Lekki',
                 'Ajah',                  'Epe',    'Lokogoma District',
                'Oredo', 'Victoria Island (VI)',           'Mowe Ofada',
                'Ikeja',
 ...
        'Ughelli South',              'Ewekoro',            'Nassarawa',
             'Mararaba',           'Uhunmwonde',        'Ughelli North',
                'Ibeju',               'Abraka',              'Paikoro',
          'Ikpoba Okha']
Length: 189, dtype: str
<StringArray>
[      'Abuja',       'Lagos',         'Edo',        'Ogun',         'Oyo',
         'Imo',    'Anambara',      'Rivers',       'Enugu',      'Kaduna',
       'Kwara',    'Nasarawa',        'Abia',       'Delta',   'Akwa Ibom',
        'Osun',       'Ekiti', 'Cross River',        'Kogi',     'Plateau',
        'Kano',     'Katsina',     'Bayelsa',       'Borno',       'Niger']
Length: 25, dtype: str
<StringArray>
[       'Detached Duplex',      'Terraced Duplexes',   'Semi Detached Duplex',
      'Detached Bungalow',         'Block of Flats', 'Semi Detached Bungalow',
      'Terraced Bungalow']
Length: 7, dtype: str

In [15]:
top_villes = df_clean['town'].value_counts().head(20).index
top_villes

Index(['Lekki', 'Ajah', 'Ikoyi', 'Ikeja', 'Ibeju Lekki',
       'Victoria Island (VI)', 'Port Harcourt', 'Ibadan', 'Gwarinpa', 'Magodo',
       'Life Camp', 'Guzape District', 'Katampe', 'Ikorodu',
       'Maitama District', 'Lokogoma District', 'Isheri North',
       'Owerri Municipal', 'Mowe Ofada', 'Isolo'],
      dtype='str', name='town')

In [16]:
df_clean['town_clean']= df_clean['town'].apply(lambda x :x if x in top_villes else "Autre")

In [17]:
df_clean['town_clean'].value_counts()

town_clean
Lekki                   10883
Autre                    4059
Ajah                     2162
Ikoyi                    1318
Ikeja                     687
Ibeju Lekki               502
Victoria Island (VI)      488
Port Harcourt             429
Ibadan                    413
Gwarinpa                  391
Magodo                    375
Life Camp                 292
Guzape District           284
Katampe                   246
Ikorodu                   241
Maitama District          226
Lokogoma District         220
Isheri North              217
Owerri Municipal          211
Mowe Ofada                180
Isolo                     176
Name: count, dtype: int64

In [18]:
df_encoded = pd.get_dummies(
    data= df_clean,
    columns=['town_clean', 'state', 'title'],
    drop_first=True
)
print(df_encoded.shape)
print(df_clean.shape)

(24000, 56)
(24000, 9)

In [31]:
df_encoded = df_encoded.drop(columns=['town'])

In [32]:
y = df_encoded['price']
X = df_encoded.drop(columns=['price'])
print(y)
print(X)

0        450000000.0
1        800000000.0
2        120000000.0
3         40000000.0
4         75000000.0
            ...
24321     15000000.0
24322     25000000.0
24323     68000000.0
24324     78000000.0
24325     65000000.0
Name: price, Length: 24000, dtype: float64
       bedrooms  bathrooms  toilets  parking_space  town_clean_Autre  \
0           6.0        5.0      5.0            4.0              True
1           4.0        5.0      5.0            4.0             False
2           4.0        5.0      5.0            4.0             False
3           4.0        4.0      5.0            6.0             False
4           4.0        4.0      5.0            2.0             False
...         ...        ...      ...            ...               ...
24321       2.0        2.0      2.0            4.0              True
24322       4.0        5.0      5.0            4.0              True
24323       4.0        5.0      5.0            4.0             False
24324       3.0        4.0      4.0            3.0             False
24325       4.0        5.0      5.0            4.0             False

       town_clean_Guzape District  town_clean_Gwarinpa  town_clean_Ibadan  \
0                           False                False              False
1                           False                False              False
2                           False                False              False
3                           False                False              False
4                           False                False              False
...                           ...                  ...                ...
24321                       False                False              False
24322                       False                False              False
24323                       False                False              False
24324                       False                False              False
24325                       False                False              False

       town_clean_Ibeju Lekki  town_clean_Ikeja  ...  state_Osun  state_Oyo  \
0                       False             False  ...       False      False
1                       False             False  ...       False      False
2                       False             False  ...       False      False
3                       False             False  ...       False      False
4                       False             False  ...       False      False
...                       ...               ...  ...         ...        ...
24321                   False             False  ...       False      False
24322                   False             False  ...       False      False
24323                   False             False  ...       False      False
24324                   False             False  ...       False      False
24325                   False             False  ...       False      False

       state_Plateau  state_Rivers  title_Detached Bungalow  \
0              False         False                    False
1              False         False                    False
2              False         False                    False
3              False         False                    False
4              False         False                    False
...              ...           ...                      ...
24321          False         False                    False
24322          False         False                    False
24323          False         False                    False
24324          False         False                    False
24325          False         False                    False

       title_Detached Duplex  title_Semi Detached Bungalow  \
0                       True                         False
1                      False                         False
2                       True                         False
3                       True                         False
4                      False                         False
...                      ...                           ...
24321                  False                         False
24322                  False                         False
24323                   True                         False
24324                  False                         False
24325                   True                         False

       title_Semi Detached Duplex  title_Terraced Bungalow  \
0                           False                    False
1                           False                    False
2                           False                    False
3                           False                    False
4                            True                    False
...                           ...                      ...
24321                       False                    False
24322                       False                    False
24323                       False                    False
24324                       False                    False
24325                       False                    False

       title_Terraced Duplexes
0                        False
1                         True
2                        False
3                        False
4                        False
...                        ...
24321                    False
24322                    False
24323                    False
24324                    False
24325                    False

[24000 rows x 54 columns]

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y ,test_size=0.2 , random_state=42)

In [34]:
len(X_train)

19200

In [35]:
len(X_test)

4800

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train ,y_train)

0.5022148798873733

In [43]:
from sklearn.metrics import mean_absolute_error , r2_score
y_predict = model.predict(X_test)
mean_absolute_error(y_test, y_predict)

73839956.35784172

In [42]:
r2_score(y_test, y_predict)

0.5022148798873733